name: Deploy to Host via FTP

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files to Host
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      env:
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      with:
        server: 169.63.229.130
        username: ${{ env.FTP_USERNAME }}
        password: ${{ env.FTP_PASSWORD }}
